{
"version":3,
"file":"module$node_modules$core_js_pure$internals$call_with_safe_iteration_closing.js",
"lineCount":1,
"mappings":"AAAAA,cAAA,CAAe,2EAAf,CAAgG,QAAQ,CAACC,MAAD,CAAQC,OAAR,CAAgBC,MAAhB,CAAuBC,OAAvB,CAAgC,CACxI,IAAIC,SAAWH,OAAA,CAAQ,sDAAR,CAGfC,OAAA,CAAOC,OAAP,CAAiBE,QAAS,CAACC,QAAD,CAAWC,EAAX,CAAeC,KAAf,CAAsBC,OAAtB,CAA+B,CACvD,GAAI,CACF,MAAOA,QAAA,CAAUF,EAAA,CAAGH,QAAA,CAASI,KAAT,CAAA,CAAgB,CAAhB,CAAH,CAAuBA,KAAA,CAAM,CAAN,CAAvB,CAAV,CAA6CD,EAAA,CAAGC,KAAH,CADlD,CAGF,MAAOE,KAAP,CAAc,CAGd,KAFIC,GAEED,CAFaJ,QAAA,CAAS,QAAT,CAEbI,CADeE,IAAAA,EACfF,GADFC,EACED,EAD0BN,QAAA,CAASO,EAAA,CAAaE,IAAb,CAAkBP,QAAlB,CAAT,CAC1BI,CAAAA,KAAN,CAHc,CAJuC,CAJ+E;",
"sources":["node_modules/core-js-pure/internals/call-with-safe-iteration-closing.js"],
"sourcesContent":["shadow$provide[\"module$node_modules$core_js_pure$internals$call_with_safe_iteration_closing\"] = function(global,require,module,exports) {\nvar anObject = require('../internals/an-object');\n\n// call something on iterator step with safe closing on error\nmodule.exports = function (iterator, fn, value, ENTRIES) {\n  try {\n    return ENTRIES ? fn(anObject(value)[0], value[1]) : fn(value);\n  // 7.4.6 IteratorClose(iterator, completion)\n  } catch (error) {\n    var returnMethod = iterator['return'];\n    if (returnMethod !== undefined) anObject(returnMethod.call(iterator));\n    throw error;\n  }\n};\n\n};"],
"names":["shadow$provide","global","require","module","exports","anObject","module.exports","iterator","fn","value","ENTRIES","error","returnMethod","undefined","call"]
}
